### ISSUE TITLE
Primus Inter Parsers references `calc` before it has been introduced

### ISSUE THREAD

**Issue by tealeg** [shriram/plai-public#2]
### Contact Details

tealeg@gmail.com

### Which part are you commenting on?

The last paragraphs and examples in "Primus Inter Parsers", foot of page 29 in my PDF

### What's the problem?

A section right at the end of "Primus Inter Parsers" (pages 29 and 30 in the PDF for electronic consumption) seems to rely on a `calc` function and a number of tests for it, being defined.  However, `calc` is first introduced in the "Evaluating Arithmetic" chapter that follows immediately after.  

Examples:

> Once we have considered these situations, we’re in a happy place, because parse produces output that **calc** can consume.

> ```(define (run s) (calc `(parse s)))```

> Compare this against the **calc** tests we had earlier!

**Comment by shriram** [comment]
Ugh, this was bad! Thanks for pointing it out.

A simple fix was to move the parsing chapter one chapter later, which has the advantages that

- we get from AST *representation* to *evaluation* right away, without interruption, and
- we've motivated the reader to care about this problem (from the perspective of testing)

Everything hangs together now.

Slated for next release.
