### ISSUE TITLE
A few typos in first half of the book

### ISSUE THREAD

**Issue by ianarawjo** [shriram/plai-public#3]
### Contact Details

ianarawjo@gmail.com

### Which part are you commenting on?

The first half of the book; page numbers below

### What's the problem?

I found some (sparingly few!) typos while reading the first half of this edition, and wanted to share them. I still have the back half of the book to read, so more typos might be incoming. My page #s are from the printable PDF version.

- Page 8 — “of of” -> “of” (“the embodiment of of the computational core…”)
- Page 27 —For type naming consistency, it seems that “Expr” here should be “Exp”, since Exp is used on p22 and the calc expression on p31 uses “Exp”
- Page 50 —I am fairly sure that the fourth program under the “Static Scoping” subsection (starts on p49) should have the “let1” expression in the then branch of the if, and “4” in the else branch, so that if false produces 4. The text below it mentions that “the conditional is never taken,” which is also technically false depending on how we define conditional —the conditional is evaluated, but the else branch is taken. So maybe it could be “the conditional branch is never taken”. 
- Page 62 —The transition to Extending Tests is a bit awkward (“Not too well” should maybe be, “We’re definitely not happy,” or remove the sentence entirely)
- Page 69 —the Javascript desugaring for o.x should be o[“x”], rather than o.[“x”] 
- Page 103 —“or anything other class” -> “or any other class”

**Comment by shriram** [comment]
This is fantastic, thanks a ton!

The static scoping catch is especially subtle — I seem to have flipped the two branches _and_ flipped the condition, with each therefore invalidating the other!

I had caught two of the typos earlier; I am putting off pushing 3.2.1 for a few more days.

**Comment by zackbach** [comment]
I believe there is another typo in the third bullet point at the end of Page 17: "However, this does automatically..." -> "However, this does *not* automatically...". The current version seems to contradict information given in the preceding paragraph
