### ISSUE TITLE
Small typo on Page 17

### ISSUE THREAD

**Issue by zackbach** [shriram/plai-public#5]
### Contact Details

zack.eisbach@gmail.com

### Which part are you commenting on?

Page 17

### What's the problem?

In the third bullet point near the bottom of Page 17, I believe the text reading "However, this does automatically..." should instead read "However, this does _not_ automatically...". 

The sentence as it currently stands appears to contradict information given in the preceding paragraph.

**Comment by shriram** [comment]
You're correct! Thanks! Fixed, will push at some point.
