### ISSUE TITLE
The #lang headers in the smol tutorials are wrong

### ISSUE THREAD

**Issue by MichaelJFishman** [shriram/plai-public#6]
### Contact Details

michaeljfishman@proton.me

### What's your suggestion?

**EDIT:** I've since found the [stacker](https://github.com/LuKC1024/stacker) repo. After installing stacker, the `#lang stacker/smol/fun` works. So rather than the headers being _wrong_, it may be that the instructions in the last step of the scope tutorial omit mentioning that stacker needs to be installed.

The `#lang` headers in the smol tutorials (eg the [scope](https://script.google.com/a/brown.edu/macros/s/AKfycbz8R8BnTfQg9GErWjqt6RluW64tdgD1Bg4zCbQ6Y12_I85R3c3ihozuF3L8Ji4x-iMa/exec?tutorial=scope) tutorial)) do not work. These are the tutorials linked in the _Teach Yourself SMoL_ section of [PLAI Version 3.2.1, 2023-01-10](https://www.plai.org/3/2/PLAI%20Version%203.2.1%20electronic.pdf).

These tutorials use the `#lang` header

```racket
#lang stacker/smol/fun
```

Using these in DrRacket gives the error

```
standard-module-name-resolver: collection not found
  for module path: stacker/smol/fun/lang/reader
  collection: "stacker/smol/fun/lang"
  in collection directories:
  <collects directory>
   ... [165 additional linked and package directories]
  no package suggestions are available .
```

The correct header, according to the [smol readme](https://github.com/shriram/smol), is 

```racket
#lang smol/fun
```

I verified that the latter works, at least after following the installation instructions in the above readme.

**Comment by shriram** [comment]
Thank you. KC has edited the tutorial to now make this explicit:

![image](https://user-images.githubusercontent.com/75030/218346869-a8640ce8-7231-4877-a5a4-f363f0bfabc9.png)

Does that make sense?

**Comment by MichaelJFishman** [comment]
This makes sense. Thanks!
