### ISSUE TITLE
Broken link from "Laziness - Evaluation Strategies" to "Evaluation on Paper - Simulating an Interpreter by Hand"

### ISSUE THREAD

**Issue by MichaelJFishman** [shriram/plai-public#7]
### Contact Details

michaeljfishman@proton.me

### Which part are you commenting on?

Laziness - Evaluation Strategies

### What's the problem?

The link from _Laziness - Evaluation Strategies_ to _Evaluation on Paper - Simulating an Interpreter by Hand_ does nothing when clicked. 

The link going in the other direction _does_ work.

OS: Ubuntu 22.04.1 LTS
PDF Readers:

- Document Viewer
- Brave Browser

Book Version: Electronic 3.2.1, from [here](https://www.plai.org/3/2/PLAI%20Version%203.2.1%20electronic.pdf).

**Comment by shriram** [comment]
Yikes, I wonder how this happened. Found and fixed, thanks.
