### ISSUE TITLE
Fix the count of example expressions in Abstract Syntax

### ISSUE THREAD

**Issue by MichaelJFishman** [shriram/plai-public#8]
### Contact Details

michaeljfishman@proton.me

### Which part are you commenting on?

Abstract Syntax

### What's the problem?

>Thus, it’s as if the last two expressions above were as

```racket
(1 + 2) + 3
1 + (2 + 3)
1 + ((2 + 3) + 4)
```

These are three expressions, not two.

PLAI edition: 3.2.1

**Comment by shriram** [comment]
No, I did mean two. But it's written confusingly, so I've changed it (and in particular, put two of them on the same line, to make this clear). Thanks!
