### ISSUE TITLE
Typo in Defining the Evaluator

### ISSUE THREAD

**Issue by MichaelJFishman** [shriram/plai-public#9]
### Contact Details

michaeljfishman@proton.me

### Which part are you commenting on?

Defining the Evaluator

### What's the problem?

> In fact, we’ve glossed over something even basic

should be

> In fact, we’ve glossed over something even more basic

PLAI edition: 3.2.1

**Comment by shriram** [comment]
Thanks!

**Comment by shriram** [comment]
Btw, these edits are going into a 3.2.2 release, which I'm just waiting for GitHub to finish pushing.
